# PLACEHOLDER — replace this file during installation.
#
# From the NixOS live ISO, after partitioning and mounting your filesystems
# under /mnt, run:
#
#   nixos-generate-config --root /mnt
#
# then copy the generated file over this one:
#
#   cp /mnt/etc/nixos/hardware-configuration.nix <this-repo>/hosts/desktop/
#
# It will contain your fileSystems (btrfs subvolumes), boot.initrd modules,
# CPU microcode, and swap devices. See README.md for the full install steps.

throw "Replace hosts/desktop/hardware-configuration.nix with the file generated by `nixos-generate-config` (see README.md)"
